services:
  app:
    build:
      context: ./
      dockerfile: Dockerfile
    tty: true
    stdin_open: true
    init: true
    environment:
      TZ: Asia/Tokyo
    working_dir: /app/
    volumes:
      - ./:/app/
